### ISSUE TITLE
HTML Output

### ISSUE THREAD

**Issue by mreinstein** [carmiac/openlyric_bookmaker#1]
Have you encountered any online songbooks/pages that have a format you like?  Happy to give this a go!

**Comment by mreinstein** [comment]
I guess I could generate into one of the other output formats and use that as a starting point.

**Comment by carmiac** [comment]
I don't have a good example off the top of my head, but I was thinking about a simple two section layout.  The ToC on the left, probably collapsible for each letter, and then each song displayed in the right main area with a media player button when there is a media file.  It would be very cool if the ToC could collapse into a hamburger menu on small screens.

**Comment by mreinstein** [comment]
@carmiac  I was poking a little at this today and learned 2 things:

1. Browsers are capable of rendering xml/xslt directly
2. This repo actually already _has_ songs in `.xml` output that are viewable in the browser.  I've hosted the existing `examples/` directory on vercel to demonstrate, you can take a look here: 

https://openlyric-bookmaker.vercel.app/songs/barretts_privateers.xml
https://openlyric-bookmaker.vercel.app/songs/amazing_grace.xml
https://openlyric-bookmaker.vercel.app/songs/leave_her_johnny.xml

So you might not need a separate html generation step, except maybe producing an `index.html` page.

**Comment by carmiac** [comment]
Yeah, the nice thing about the OpenLyric format is that it came with the xslt/css to render the songs, except for the media player part.

As for the rest, I can generate an index.html, I just don't really know what it should look like so I need an example with navigation, etc.

**Comment by mreinstein** [comment]
I guess it makes most sense to generate an index page from xml/xsl, rather than building html directly, since the rest of the example code is built that way.

I haven't written xsl in like 20 years so I'll need to block off some time to dust this off, but I should be able to some point torwards the end of the week.

**Comment by carmiac** [comment]
I'm good with whatever you think is best.  Either generating html or an xml/xsl system.  Thanks!
